### ISSUE TITLE
Error input (path) IslandCompare

### ISSUE THREAD

**Issue by antoniocamillo** [brinkmanlab/islandcompare-cli#3]
First I would like to congratulate you for the great work on IslandCompare. For sure the results generated by the application will contribute a lot to the scientific community. I would like your help, to understand a possible mistake when I'm trying to run locally.

As per the instructions, I tried to run it with the following arguments described below. None of them were successful, always with ERROR: Invalid dataset path specified. What would be the correct arguments to run locally?

-h
usage: islandcompare.py upload_run [-h] [-r REFERENCE_ID] [-a NEWICK_PATH | -l NEWICK_PATH] analysis_label path [path ...] output_path

https://github.com/brinkmanlab/islandcompare-cli
./islandcompare.py --key MYAPIKEY upload_run 'Analysis label' ./path/to/data/*.gbk ./output/

./islandcompare.py --key XXX upload_run analysis_label ./home/islandcompare/data/*.gbk ./home/islandcompare/output

./islandcompare.py --key XXX upload_run analysis_label /home/islandcompare/data/*.gbk /home/islandcompare/output

./islandcompare.py --key XXX upload_run analysis_label path /home/islandcompare/data/*.gbk output_path /home/islandcompare/output

./islandcompare.py --key XXX upload_run analysis_label path ./home/islandcompare/data/*.gbk output_path ./home/islandcompare/output

./islandcompare.py --key XXX upload_run analysis_label path [/home/islandcompare/data/*.gbk] output_path /home/islandcompare/output

./islandcompare.py --key XXX upload_run analysis_label path [/home/islandcompare/data/*.gbk] output_path ./home/islandcompare/output

Best regards.

**Comment by innovate-invent** [comment]
Hello and thank you for your interest in IslandCompare. 

It looks like you need to ensure you are providing the correct paths to your data, try running `ls <path>` to verify that you are referring to a file that exists. See https://www.geeksforgeeks.org/absolute-relative-pathnames-unix/

Please also do not make public your API key, anyone with it can access and delete your data.

**Comment by antoniocamillo** [comment]
> Hello and thank you for your interest in IslandCompare.
> 
> It looks like you need to ensure you are providing the correct paths to your data, try running `ls <path>` to verify that you are referring to a file that exists. See https://www.geeksforgeeks.org/absolute-relative-pathnames-unix/
> 
> Please also do not make public your API key, anyone with it can access and delete your data.

Thanks for your feedback, but there is no problem (i think) with the path.
![running](https://user-images.githubusercontent.com/99414327/179568373-fdb4dd51-4fad-4d4a-97e9-8928862b8649.png)

![path](https://user-images.githubusercontent.com/99414327/179568429-7f038ad8-9053-4d7c-9313-21bf014c3052.png)

**Comment by innovate-invent** [comment]
Please try running `ls <path>` on your provided path to verify.

**Comment by antoniocamillo** [comment]
> Thanks for your feedback again.

I just put ' ' in the label and works ... sorry for the inconvenience.

Best regards
